### ISSUE TITLE
Windows path separators used in cpp file

### ISSUE THREAD

**Issue by jbeale1** [pranjal-joshi/TSD305Lib-Arduino#1]
Thank you for providing this library. I just wanted to note that it will not compile as-is under linux, because line 13 of TSD305lib.cpp contains a backslash:

	#include <avr\pgmspace.h>

this does not work on Linux OS. If you use a forward slash, it works on both Windows and Linux.

	#include <avr/pgmspace.h>

**Comment by pranjal-joshi** [comment]
@jbeale1 fixed in 6b21a28
